name: ModularMSMF
main: main.ModularMSMF
version: FUCKING NEU
authors: [Lightkeks, ernikillerxd64]

commands:
  mmsmf:
    description: Zeigt Infos und mehr an.
    usage: /<command> <args>
    aliases: <info>
  teleport:
    description: teleportation zu einem Spieler.
    usage: /<command> <target>
    aliases: <tp, tele>
  heal:
    description: Heilt Spieler.
    usage: /<command> <target>
  eco:
    description: Geldstand anzeigen oder anderes.
    usage: /<command> <args>
  feed:
    description: Saettigt den Spieler.
    usage: /<command> <player>
  ban:
    description: Bannt einen Spieler.
    usage: /<command> <player>
  unban:
    description: Entbannt einen Spieler.
    usage: /<command> [args] <player>
  kick:
    description: Kickt einen Spieler.
    usage: /<command> <player>
  kill:
    description: Killt einen Spieler.
    usage: /<command> <args>
  mute:    
    description: Mutet einen Spieler.
    usage: /<command> <player>
  getserver:
    description: Gibt die Serversoftware an.
    usage: /<command>
  motd:
    description: Message Of The Day.
    usage: /<command> <args>
  slaughter:
    description: Destroy entities.
    usage: bla
  language:
    description: Choose your language.
    usage: /<command> <args>
  home:
    description: Teleports you home. Optionally specify a home name.
    usage: /<command> <args>
  sethome:
    description: Sets a home.
    usage: /<command> <args>
  test:
    description: Testing purposes only
    usage: /<command>
  setspawn:
    description: Set the spawn
    usage: /<command>
  spawn:
    description: Spawns the player
    usage: /<command>